name: SelfHosted test

on:
  push:

jobs:
  arm-gcc-build-selfhosted:
    name: FreeRTOS ARM GCC Build Check
    runs-on: fargate-medium-ubuntu-gcc-armnoneeabi-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
        with:
            path: ./workspace
            submodules: 'recursive'
            fetch-depth: 1
      - name: Qemu MPS2 build Cortex M3
        run: cd workspace/FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC && make && make clean && make FULL_DEMO=1
      - name: Qemu MPS2 MPU build Cortex M3
        run: cd workspace/FreeRTOS/Demo/CORTEX_MPU_M3_MPS2_QEMU_GCC && make
      - name: Qemu MPS2 IAR build Cortex M3
        run: cd workspace/FreeRTOS/Demo/CORTEX_MPS2_QEMU_IAR_GCC/build/gcc && sed -i '/configUSE_STATS_FORMATTING_FUNCTIONS/c\#define configUSE_STATS_FORMATTING_FUNCTIONS 0' ../../FreeRTOSConfig.h && make
